### ISSUE TITLE
schema.rb has no type for index

### ISSUE THREAD

**Issue by kuon** [TalentBox/sequel-rails#103]
When I create an index with:

```
      index :location, type: :gist
```

in my migration, it generates:

```
      index [:location]
```

In my `schema.rb`.

The type of the index is lost, and thus the table cannot be restored as postgresql fails with:

`ERROR:  data type point has no default operator class for access method "btree"`

**Comment by JonathanTron** [comment]
Hi @kuon,
thanks for reporting the issue.

Unfortunately we're only using the schema dumper from `Sequel`, which has this kind of limitation (probably because `schema.rb` is meant to be as database agnostic as possible).

If you want to dump this kind of database specific information you should configure `sequel-rails` to dump the schema in sql format (using `pg_dump` for postgresql).

You can do it by setting the following in your `config/application.rb`:

```ruby
config.sequel.schema_format = :sql
```

**Comment by kuon** [comment]
I see, thanks!
