### ISSUE TITLE
Is there a way to disable generators conflicting with ActiveRecord?

### ISSUE THREAD

**Issue by managr** [TalentBox/sequel-rails#84]
I'm using sequel together with active-record. I was able to successfully disable sequel rake tasks using:
```
config.sequel.load_database_tasks = false
```

But if I try to generate new migration using:
```
rails g migration migration_name
```
it is using sequel generator to generate the migration code. Is there a way to configure rails not to pick up sequel generator before active-record one?

**Comment by JonathanTron** [comment]
No, there is currently nothing to configure sequel-rails so that it don't set himself as generator for orm.

The line which add this is: https://github.com/TalentBox/sequel-rails/blob/master/lib/sequel_rails/railtie.rb#L26.

We can add a configuration like the `load_database_tasks` or `skip_connect` and then move the previously mentioned line in a new initializer (otherwise we would never see an override to this config).

Do you want to send a PR for it?

**Comment by managr** [comment]
Thanks Jonathan for pointing me to the code. Looking at that I was able to override back the generators to AR ones using this in ```application.rb```:
```
    config.app_generators.orm :active_record, :migration => true, :timestamps => true
```
So I'm fine with that solution. Closing. Thanks.

**Comment by JonathanTron** [comment]
You're welcome.
