### ISSUE TITLE
How to use togheter with ActiveRecord?

### ISSUE THREAD

**Issue by brauliobo** [TalentBox/sequel-rails#88]
Sorry for asking questions here.

I'm have a large AR based project, I would like to introduce the use of Sequel with sequel-rails.

I've included it on my Gemfile, but DB is not loaded. Can sequel-rails work alongside with AR?

**Comment by JonathanTron** [comment]
As far as I know, there's no problem using both except for the database rake tasks which you need to disable for sequel-rails: `config.sequel.load_database_tasks = false`

**Comment by JonathanTron** [comment]
How do you try to access the db? From your message it looks like you expect some kind of global `DB` to be set. sequel-rails don't do this, nor does Sequel, if you want to access the db you should use `Sequel::Model.db`.

**Comment by fnordfish** [comment]
Just figured out a minor quirks and like to put it for reference:

I'm using sequel inside an in-app rails engine. In order to not "mess" with the main apps configuration I had to reset the app generators like this:

`config.app_generators.orm :active_record, migration: true, timestamps: true`

(Maybe this could be made configurable somehow?)
